version: "3"
services:
  # python-app:
  #  image: python:latest
  #  volumes:
  #    - ./app:/app
  #  command:
  #    - "python"
  #    - "/app/app.py"

  nginx-server:
    image: nginx:latest
    volumes:
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/config:/etc/nginx/
      - ./nginx/www:/var/www/teamled/
    ports:
      - "9080:80"

  mysql-db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: your_database
      MYSQL_USER: your_user
      MYSQL_PASSWORD: your_password
    volumes:
      - ./mysql:/var/lib/mysql

  wordpress:
    image: wordpress:latest
    environment:
      WORDPRESS_DB_HOST: mysql-db
      WORDPRESS_DB_USER: your_user
      WORDPRESS_DB_PASSWORD: your_password
      WORDPRESS_DB_NAME: your_database

    volumes:
      - ./wordpress:/var/www/html
    ports:
      - "8000:80"
    depends_on:
      - mysql-db

#  backup:
#    image: # Add Docker image name here.
#    volumes:
#      - ./backup:/backup
#    depends_on: # Add services that this service depends on (have to start before backup container so backup get latest files).
#      - mysql-db
#      - wordpress