# Going to work with this during the weekend and try to implement stuff we want from the upcoming PDF-file.
# Please upload any code to Github before friday ends <3.

version: "3"
services:
  python-app:
    image: python:latest
    volumes:
      - ./app:/app
    command:
      - "python"
      - "/app/app.py"

  nginx-server:
    image: nginx:latest
    volumes:
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/config:/etc/nginx/
      - ./nginx/www:/var/www/teamled/
    ports:
      - "9080:80"

  mysql-db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: your_database
      MYSQL_USER: your_user
      MYSQL_PASSWORD: your_password

  wordpress:
    image: wordpress:latest
    volumes:
      - ./wordpress:/var/www/html
    ports:
      - "8000:80"

#  backup:
#    image: # Add Docker image name here.
#    volumes:
#      - ./backup:/backup
#    depends_on: # Add services that this service depends on (have to start before backup container so backup get latest files).
#      - mysql-db
#      - wordpress